### ISSUE TITLE
Removing Additional columns in final tables

### ISSUE THREAD

**Issue by vinod-rajasekaran** [DevDataPlatform/dbt_stir#7]
1. Hashid columns can be removed from final production tables:

_airbyte_delhi_india__ment_form_2022_hashid | TEXT |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
  | _airbyte_indonesia_stir_bm_2022_hashid | TEXT |   |   |   |   |  
  | _airbyte_karnataka_stir_bm_2022_hashid | TEXT |   |   |   |   |  
  | _airbyte_tn_stir_bm_2022_hashid | TEXT |   |   |   |   |  
  | _airbyte_uganda_bm_2022_hashid

2.Uganda and Indonesia - all districts are not being coalesced and excluded: fields are: 

district_acholi | TEXT |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
  | district_bunyoro | TEXT |   |   |   |   |  
  | district_busoga | TEXT |   |   |   |   |  
  | district_central | TEXT |   |   |   |   |  
  | district_karamoja | TEXT |   |   |   |   |  
  | district_kigezi | TEXT |   |   |   |   |  
  | district_kota_kediri | TEXT |   |   |   |   |  
  | district_lango | TEXT |   |   |   |   |  
  | district_masaka | TEXT |   |   |   |   |  
  | district_mbale | TEXT |   |   |   |   |  
  | district_midwestern | TEXT |   |   |   |   |  
  | district_rwenzori | TEXT |   |   |   |   |  
  | district_teso | TEXT |   |   |   |   |  
  | district_westnile

3. Karnataka form:
division_kt does not need to go into final table?

4. forms_uganda and forms_indonesia can be excluded as they are coalesced into forms

5. location_indonesia and location_uganda should have been coalesced into region and can be excluded form final table

6. for sake of easier maintenance create forms_verbose in final merged table rather than across all five intermediate transforms.

Can I  review before merge into master and  push

**Comment by vinod-rajasekaran** [comment]
Also add forms_verbose to https://github.com/DevDataPlatform/dbt_stir/blob/main/models/production/classroom_surveys/derived/classroom_surveys_normalized.sql

**Comment by siddhant3030** [comment]
Remove district_kota_kediri from indonesia table

**Comment by siddhant3030** [comment]
remove location_indonesia and uganda from final table
